---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: dev
  namespace: clusters
spec:
  id: dev
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: medium
    minNodeCount: 1
  writeConnectionSecretToRef:
    name: cluster-dev

---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: GitOpsClaim
metadata:
  name: dev
  namespace: clusters
spec:
  id: dev
  compositionSelector:
    matchLabels:
      provider: fleet
      initiate-by: manager
  parameters:
    kubeConfig:
      secretName: cluster-dev
      secretNamespace: clusters
    environment: dev
    gitOpsRepo: https://github.com/vfarcic/devops-toolkit-crossplane.git