---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: dev
  namespace: cluster
spec:
  id: dev
  compositionSelector:
    matchLabels:
      provider: civo
      cluster: ck
  parameters:
    nodeSize: medium
    minNodeCount: 3
  writeConnectionSecretToRef:
    name: cluster-dev