---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: CompositeCluster
metadata:
  name: dev
spec:
  id: dev
  compositionRef:
    name: cluster-civo
  parameters:
    nodeSize: small
    minNodeCount: 3
