---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: CompositeCluster
metadata:
  name: production
spec:
  id: production
  compositionRef:
    name: cluster-civo
  parameters:
    nodeSize: small
    minNodeCount: 3
