---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: CompositeCluster
metadata:
  name: staging
spec:
  id: staging
  compositionRef:
    name: cluster-civo
  parameters:
    nodeSize: small
    minNodeCount: 3
