---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: {{ .Chart.Name }}
spec:
  id: {{ .Chart.Name }}
  compositionSelector:
    matchLabels:
      type: backend-db
  parameters:
    namespace: production
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    port: 8080
    host: "{{ .Values.ingress.host }}"

---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: {{ .Chart.Name }}
spec:
  id: {{ .Chart.Name }}
  compositionSelector:
    matchLabels:
      provider: "{{ .Values.db.provider }}"
      db: postgresql
  parameters:
    version: "13.4"
    size: small
    namespace: production
  writeConnectionSecretToRef:
    name: {{ .Chart.Name }}
