---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: GitOpsClaim
metadata:
  name: dev-agent
  namespace: clusters
spec:
  id: dev
  compositionSelector:
    matchLabels:
      provider: fleet
      initiate-by: manager
  parameters:
    kubeConfig:
      secretName: cluster-dev
      secretNamespace: clusters
    environment: dev
    gitOpsRepo: https://github.com/vfarcic/devops-toolkit-crossplane.git
