---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: GitOpsClaim
metadata:
  name: production-01-agent
  namespace: clusters
spec:
  id: production-01
  compositionSelector:
    matchLabels:
      provider: fleet
      initiate-by: manager
  parameters:
    kubeConfig:
      secretName: cluster-production-01
      secretNamespace: clusters
    environment: production
    gitOpsRepo: https://github.com/vfarcic/devops-toolkit-crossplane.git

---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: GitOpsClaim
metadata:
  name: production-02-agent
  namespace: clusters
spec:
  id: production-02
  compositionSelector:
    matchLabels:
      provider: fleet
      initiate-by: manager
  parameters:
    kubeConfig:
      secretName: cluster-production-02
      secretNamespace: clusters
    environment: production
    gitOpsRepo: https://github.com/vfarcic/devops-toolkit-crossplane.git
