---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: GitOpsClaim
metadata:
  name: staging-agent
  namespace: clusters
spec:
  id: staging
  compositionSelector:
    matchLabels:
      provider: fleet
      initiate-by: manager
  parameters:
    kubeConfig:
      secretName: cluster-staging
      secretNamespace: clusters
    environment: staging
    gitOpsRepo: https://github.com/vfarcic/devops-toolkit-crossplane.git
